# Generated by Django 4.1.1 on 2022-09-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=70)),
                ('text', models.TextField(blank=True)),
                ('header_color', models.CharField(default='dark', max_length=30)),
                ('author', models.IntegerField(default=1)),
                ('amount_likes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'posts_list',
            },
        ),
    ]
