# Generated by Django 4.1.1 on 2022-09-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
