# Generated by Django 4.1.1 on 2022-10-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_postlike'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentlike',
            table='comment_like',
        ),
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='postlike',
            table='post_like',
        ),
    ]
