# Generated by Django 4.1.1 on 2022-10-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_commentlike_table_alter_comments_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentlike',
            table='comments_likes',
        ),
        migrations.AlterModelTable(
            name='postlike',
            table='posts_likes',
        ),
    ]
