# Generated by Django 4.1.1 on 2022-10-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customeruser_image_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='image_profile',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
