# Generated by Django 4.1.1 on 2022-10-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customeruser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
